services:
  # Our PostgreSQL database
  db:
    image: postgres:latest
    ports:
      - "5437:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprod!

 # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8088:8080